name: RareItemHunter2
main: com.ne0nx3r0.rih.RareItemHunterPlugin
version: '2.6.22a'
load: STARTUP
database: false
softdepend: [Essentials]
description: Rare Item Hunter
commands:
    ri:
      description: RareItems commands
    hat:
      description: put an item on your head
permissions: 
# All
  rih.tester:
    description: Permission to test ALL the things
    default: false